### ISSUE TITLE
Redo doesn't have a shortcut

### ISSUE THREAD

**Issue by daf0x** [magnush/mhwaveedit#10]
While undo has a shortcut (Ctrl+Z), redo does not. This makes it inconvenient to use undo/redo to e.g. compare the result of applying an effect. Please add Ctrl+Shift+Z as a the shortcut for redo.

**Comment by magnush** [comment]
Closing issue, this has been fixed in the release 1.4.24..

**Comment by lucmp** [comment]
I hate Ctrl+Shift+Z. Please consider making it possible to add custom keyboard shortcuts. It's the only thing I really miss in this great editor.
Don't bother with a fancy GUI, a plain text config file will be fine.
