### ISSUE TITLE
Suggestion; try http://libsound.io/

### ISSUE THREAD

**Issue by ghost** [magnush/mhwaveedit#17]
http://libsound.io/ is cross-platform/multiple-backends C library; could it used to modernize mhwaveedit (so it can work with alsa, pulseaudio and jackd)?

**Comment by magnush** [comment]
mhwaveedit already works very well with both alsa, pulseaudio and jack, and has for many years. You may have a version where the support has been compiled out however, or if you compiled it yourself you may be missing some devel packages.

**Comment by ghost** [comment]
I was not aware that mhwaveedit already support alsa, pulseaudio and jackd, so opening that issue was irrelevant. But since libsoundio also support Windows and OSX, it could help porting mhwaveedit to Windows and OSX, as an alternative to Audacity; multi-platform compatibility a good criteria to adopt a software.
