### ISSUE TITLE
Icon not suitable for AppStream

### ISSUE THREAD

**Issue by gkarsay** [magnush/mhwaveedit#7]
AppStream generator is extracting meta data from packages in Debian, also mhwaveedit. It has different requirements than freedesktop.org, though. The icon should be at least 64x64px in size, should be in .png or .svg format and should be placed in /usr/share/icons/hicolor/%{size}/apps/ , see https://wiki.debian.org/AppStream/Guidelines#Icon_best_practices

Although the issue is solved in Debian by installing such an icon (converted to .png and upscaled), please consider adding it to source and installing it at /usr/share/icons/hicolor/64x64/apps/

![mhwaveedit](https://user-images.githubusercontent.com/8670449/43363274-a8c14c3e-9301-11e8-8d60-770a3697f3aa.png)

**Comment by magnush** [comment]
Fixed in release 1.4.24
