### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by trebmuh** [magnush/mhwaveedit#8]
Hi @magnush

The last release dates back [from August 2013](https://github.com/magnush/mhwaveedit/releases/tag/v1.4.23).

A new release would contains: 
- Italian and French translation update
- desktop file update
- fix build on hurd

As can be seen [here](https://github.com/magnush/mhwaveedit/compare/v1.4.23...master).

What about releasing a new version?

**Comment by magnush** [comment]
Yeah you're right I have not been very active on this project the last couple of years for various reasons. I will see if I can make a release to get the stuff out. The platform I was using previously to distribute releases (gna.org) is now closed down so my plan is to try and do releases directly on Github instead but I will need to change a few things in how I do releases for that to work well.

**Comment by trebmuh** [comment]
Nice !

**Comment by trebmuh** [comment]
Nice. Thanks @magnush !
